Itinerary export: travelIndex numbers each stop of a tour
cestastanford/grandtour pull request #160
Opened 2019-07-25 22:12 UTC by ryanctan

Fixes #129.

2019-07-27 23:00 UTC, epicfaace requested changes
Looks good, just a small comment.

We should also eventually document somewhere that both the travelIndex and travelindexTotal fields are no longer used and irrelevant to the data itself (since the index is only determined by the position of the travel in the array). (https://github.com/cestastanford/grandtour/blob/ae77ab4ba17d4084a4aedfaaf46b05a511808c40/models/entry-fields/travels.js#L19)

2019-07-27 23:00 UTC, epicfaace commented on query.js
>          if (d.travels && d.travels.length) d.travels.forEach(a => travels.push({
To make this code a bit more readable, I would suggest doing something like this: 

```suggestion
        if (d.travels && d.travels.length) d.travels.forEach((a, i) => travels.push({
```

This would make `i` equal to the index. Then you can set travelIndex to `i + 1`.

2019-07-29 17:56 UTC, ryanctan commented
@epicfaace changes made and ready for review, index was also changed to zero-based

2019-07-29 18:09 UTC, epicfaace commented
Thanks. I don't think "trivial" may be the right word - these fields are more "unused" and should probably eventually be deleted from the database.

2019-07-29 18:20 UTC, ryanctan commented
@epicfaace done!

2019-07-29 18:35 UTC, epicfaace approved these changes

2019-07-29 18:41 UTC, merged